package cursor.rybak.model.race;

public interface CalcConst {
    double INCREASE_XP_COEFFICIENT_PER_CHARISMA = 0.02;
    double INCREASE_HP_COEFFICIENT_PER_STAMINA = 2;
    double INCREASE_MP_COEFFICIENT_PER_INTELLECT = 2;
    double INCREASE_RP_COEFFICIENT_PER_AGILITY = 4;

    double REGEN_HP_COEFFICIENT_PER_STAMINA = 0.25;
    double REGEN_MP_COEFFICIENT_PER_INTELLECT = 0.25;
    double REGEN_MP_COEFFICIENT_PER_CONCENTRATION = 1.5;
    double REGEN_HP_COEFFICIENT_PER_CONCENTRATION = 1;
    double REGEN_RP_COEFFICIENT_PER_CONCENTRATION = 1;
}
